[package]
name = "hysteresis"
version = "1.0.3"
license = "MIT"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
const-str = "0.5.7"
num-traits = "0.2.19"
vapours = "0.1.2"
vapoursynth4-rs = "0.3.0"

[profile.release]
codegen-units = 1
lto = true
