name: Publish

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  build-sdist:
    name: build-sdist (${{ matrix.target }})
    runs-on: ubuntu-24.04

    permissions:
      id-token: write
      contents: read
      attestations: write

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
        with:
          target: ${{ matrix.target }}
          toolchain: nightly

      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0

      - name: Build sdist
        run: uv build --sdist

      - name: Attest build provenance
        uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4.1.0
        if: ${{ github.event_name == 'push' }}
        with:
          subject-path: dist/*.tar.gz

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: vapoursynth-hysteresis-sdist
          path: ./dist/*.tar.gz

  build-wheels:
    name: build-wheels (${{ matrix.target }})

    permissions:
      id-token: write
      contents: read
      attestations: write

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-gnu
          - os: macos-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
        with:
          target: ${{ matrix.target }}
          toolchain: nightly

      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0

      - name: Build wheels
        uses: pypa/cibuildwheel@8d2b08b68458a16aeb24b64e68a09ab1c8e82084 # v3.4.1

      - name: Attest build provenance
        uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4.1.0
        if: ${{ github.event_name == 'push' }}
        with:
          subject-path: wheelhouse/*.whl

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: vapoursynth-hysteresis-wheels-${{ matrix.runs-on }}
          path: ./wheelhouse/*.whl

  publish:
    needs: [build-wheels, build-sdist]
    name: publish
    runs-on: ubuntu-24.04

    environment:
      name: pypi
      url: https://pypi.org/p/vapoursynth-hysteresis

    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: vapoursynth-hysteresis-*
          path: dist
          merge-multiple: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
